// Listar todas
GET http://localhost:8080/tasks

### Buscar 1
GET http://localhost:8080/tasks/1


### Agregar tarea
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "title": "Let me be ",
    "isDone": false
}

### Editar tarea 1
PUT http://localhost:8080/tasks/1
Content-Type: application/json

{
    "title": "Aprender Node.js",
    "isDone": true
}

### Borrar tarea 1
DELETE http://localhost:8080/tasks/2

### Query
GET http://localhost:8080/search?query=let